### ISSUE TITLE
No issue when Python is not found

### ISSUE THREAD

**Issue by yannmh** [DataDog/gohai#12]
```
checks.collector(collector.pyc:649) | GOHAI LOG | 2015/06/18 07:42:07 [platform] exec: "python": executable file not found in %PATH%
```

from https://github.com/DataDog/gohai/blob/46c8b19506a267af8ae73a6cef860dfb7f63f727/platform/platform_common.go#L45

**Comment by olivielpeau** [comment]
We should probably remove this log line as it can be misleading for users, and provides no useful information about the agent's environment (given that it's testing the system python).

**Comment by remh** [comment]
we should actually just remove it
the agent collects that

**Comment by Chillguy** [comment]
This error has shown up in between 2 (missing) lines every time my host has been sending false positive alerts of being down. So far it's the only 'error' I can correlate to the times whatsoever. Almost 6 months later and its still not removed? Any update on this?

**Comment by djmitche** [comment]
This message does not appear to be logged anymore.
