### ISSUE TITLE
missing default case in computeCoresAndProcessors switch

### ISSUE THREAD

**Issue by fgenolini** [DataDog/gohai#186]
https://github.com/DataDog/gohai/blob/master/cpu/cpu_windows_amd64.go#L213

missing:
```go
default:
  bufused += info.Size - 8
```

because `cpu_windows_amd64.go` does not handle the remaining cases (`RelationProcessorModule`, `RelationProcessorDie`, `RelationNumaNodeEx`...), so the default statement is needed to correctly advance the `bufused`.

**Comment by pgimalac** [comment]
Closed in favor of https://github.com/DataDog/datadog-agent/issues/17571 (thanks for opening it there too !)
