### ISSUE TITLE
Add platform version

### ISSUE THREAD

**Issue by tmichelet** [DataDog/gohai#2]
The goal is to have a field like "Ubuntu 12.04.3 LTS"

```
cat /etc/lsb-release | grep DISTRIB_DESCRIPTION
DISTRIB_DESCRIPTION="Ubuntu 12.04.3 LTS"
```
see https://github.com/opscode/ohai/blob/master/lib/ohai/plugins/linux/platform.rb

cc @remh

**Comment by remh** [comment]
The agent already collects that (not in gohai though). Closing.
