### ISSUE TITLE
Report the number of logical processors

### ISSUE THREAD

**Issue by JohnLZeller** [DataDog/gohai#21]
Gohai reports the number of physical cores on the host; which is does correctly. However, when using AWS, they provision instances with some number of vCPUs, which causes some confusion. Each vCPU is just half of a physical core, so if there are 16 vCPUs on an instance, then gohai will report 8 cores, because there are only 8 physical cores, and 16 logical processors.

When you test this on a Windows AMI with 16 vCPUs, you'll see that wmi shows NumberOfCores at 8 and NumberOfLogicalProcessors at 16.

Shall we add another count for this?

**Comment by JohnLZeller** [comment]
Here is a PR for this, in gohai: https://github.com/DataDog/gohai/pull/22

**Comment by JohnLZeller** [comment]
PR for dogweb: https://github.com/DataDog/dogweb/pull/11029

**Comment by olivielpeau** [comment]
Fixed by the PRs above. Closing. Thanks @JohnLZeller !
