### ISSUE TITLE
[windows] IPv6 reports with interface as part of string

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/gohai#35]
This is likely because we're fetching the IP in a custom fashion. For example a host may end up with an ipv6 value that looks like:

```
fe80::b918:d6c8:4471:7907%12
```

While this is part of [the spec](https://en.wikipedia.org/wiki/IPv6_address#Link-local%5Faddresses%5Fand%5Fzone%5Findices) we should match the linux check and just report the inet address without including the interface.

**Comment by pgimalac** [comment]
Hello, this repository has been archived, the gohai library now lives in https://github.com/DataDog/datadog-agent/pkg/gohai, feel free to re-open your issue in https://github.com/DataDog/datadog-agent if it is still relevant.
