### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by urosgruber** [DataDog/gohai#38]
I'm working on datadog agent FreeBSD port and since latest version this library is used to get sysinfo data. 

Right now BSD is not supported. But nice thing is everything is pretty similar how Darwin works. 

Could someone give some detail how and where to start with this without copying every darwin file to freebsd. Could we use some alias or something?

**Comment by olivielpeau** [comment]
Hi @urosgruber, thanks for your interest in porting gohai to FreeBSD 😄 

To define os-specific code in go you can either suffix the file name with `_$GOOS` (for example `_darwin` **or** define under which platforms a file should be built with the `// +build` tag (see https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool for more details)

So if there's a file that you think could be shared between darwin and FreeBSD you could rename `<file>_darwin.go` to `<file>_bsd.go` (the `_bsd` suffix here is not picked up by `go build` but is just here for clarity) and add the `// +build darwin freebsd` annotation at the top of the file.

If the code can't be shared then we should have 2 different files, `_darwin` and `_freebsd`.

Does this answer your question?

Also, just so you know, the `processes` package is not used to get sysinfo data (it's called separately by the agent's collector to retrieve information about running processes), so you can probably ignore it.

Let us know if you have any questions!

**Comment by urosgruber** [comment]
@olivielpeau thanks for clarify things. I'll try to do my best because this is right now a blocker for BSD support on latest datadog. I'll open PR when done.

**Comment by urosgruber** [comment]
@olivielpeau made a PR for FreeBSD support. Tested on 3 servers.

**Comment by lgadalla-impinj** [comment]
`sysman@vault-test:~/go/src/github.com/DataDog $ git clone https://github.com/DataDog/gohai.git
Cloning into 'gohai'...
remote: Enumerating objects: 1502, done.
remote: Counting objects: 100% (1501/1501), done.
remote: Compressing objects: 100% (594/594), done.
remote: Total 1502 (delta 891), reused 1419 (delta 879), pack-reused 1
Receiving objects: 100% (1502/1502), 1.76 MiB | 22.83 MiB/s, done.
Resolving deltas: 100% (891/891), done.
sysman@vault-test:~/go/src/github.com/DataDog $ cd gohai/
sysman@vault-test:~/go/src/github.com/DataDog/gohai $ go build
# github.com/DataDog/gohai/filesystem
filesystem/filesystem_common.go:23:16: undefined: getFileSystemInfo
# github.com/DataDog/gohai/memory
memory/memory.go:28:16: undefined: getMemoryInfo
memory/memory.go:44:30: undefined: getMemoryInfoByte
# github.com/DataDog/gohai/cpu
cpu/cpu.go:63:16: undefined: getCPUInfo
cpu/cpu.go:71:18: undefined: getCPUInfo
# github.com/DataDog/gohai/processes
processes/processes_common.go:38:19: undefined: getProcesses
# github.com/DataDog/gohai/platform
platform/platform.go:61:22: undefined: GetArchInfo
sysman@vault-test:~/go/src/github.com/DataDog/gohai $ uname -a
FreeBSD myhostname 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64`

**Comment by lgadalla-impinj** [comment]
```
sysman@vault-test:~/go/src/github.com/DataDog $ git clone https://github.com/DataDog/gohai.git
Cloning into 'gohai'...
remote: Enumerating objects: 1502, done.
remote: Counting objects: 100% (1501/1501), done.
remote: Compressing objects: 100% (594/594), done.
remote: Total 1502 (delta 891), reused 1419 (delta 879), pack-reused 1
Receiving objects: 100% (1502/1502), 1.76 MiB | 22.83 MiB/s, done.
Resolving deltas: 100% (891/891), done.
sysman@vault-test:~/go/src/github.com/DataDog $ cd gohai/
sysman@vault-test:~/go/src/github.com/DataDog/gohai $ go build
# github.com/DataDog/gohai/filesystem
filesystem/filesystem_common.go:23:16: undefined: getFileSystemInfo
# github.com/DataDog/gohai/memory
memory/memory.go:28:16: undefined: getMemoryInfo
memory/memory.go:44:30: undefined: getMemoryInfoByte
# github.com/DataDog/gohai/cpu
cpu/cpu.go:63:16: undefined: getCPUInfo
cpu/cpu.go:71:18: undefined: getCPUInfo
# github.com/DataDog/gohai/processes
processes/processes_common.go:38:19: undefined: getProcesses
# github.com/DataDog/gohai/platform
platform/platform.go:61:22: undefined: GetArchInfo
sysman@vault-test:~/go/src/github.com/DataDog/gohai $ uname -a
FreeBSD vault-test.impinj.com 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64
```

**Comment by pgimalac** [comment]
Hello, this repository has been archived, the gohai library now lives in https://github.com/DataDog/datadog-agent/pkg/gohai, feel free to re-open your issue in https://github.com/DataDog/datadog-agent if it is still relevant.
