### ISSUE TITLE
GOHAI LOG | Error fetching info for pid 4844: strconv.ParseInt: parsing ")": invalid syntax

### ISSUE THREAD

**Issue by tmadej** [DataDog/gohai#40]
This error started happening today:

| WARNING | dd.collector | checks.collector(collector.py:790) | GOHAI LOG | Error fetching info for pid 4844: strconv.ParseInt: parsing ")": invalid syntax

PID:

4844     1  0 04:17 ?        00:00:00 cpsrvd (SSL) - waiting f --llu=1480496055 --listen=3,4,5,6,7,8,9,10 --accepted=11

Looks like the parser is breaking on the parentheses causing datadog to report no data for this host. Could you fix asap?

**Comment by olivielpeau** [comment]
Thanks @tmadej for reporting this issue. These gohai failures shouldn't cause the Agent to report no data though.

To allow us to troubleshoot this further, could you send a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) to our support team from the affected Agent?

**Comment by ringerc** [comment]
Causes noise in otel collector datadog exporter see  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14186

Related: https://github.com/DataDog/gohai/issues/37

**Comment by pgimalac** [comment]
Hello, this repository has been archived, the gohai library now lives in https://github.com/DataDog/datadog-agent/pkg/gohai, feel free to re-open your issue in https://github.com/DataDog/datadog-agent if it is still relevant.
