### ISSUE TITLE
CPU stuck on AWS

### ISSUE THREAD

**Issue by yaronlev171** [DataDog/gohai#43]
The machine is a AWS c4.8xlarge with 36 cores. OS is RHEL, SELinux enabled. CPU 28 got stuck "blaming" gohai. The machine was quite idle at 3% cpu. 
When this happened we got a datadog alert, and cpu spiked to 10%, and never let down. The CPU did not recover so we had to restack the instance.

This is the first time we see this.

Logs (a combination of datadog logs, /var/log/messages and audit.logs attached.
[datadog_gohai_logs.txt](https://github.com/DataDog/gohai/files/737034/datadog_gohai_logs.txt)

**Comment by olivielpeau** [comment]
Hi @yaronlev171, have you seen this error happen again?

To troubleshoot this we'd need a more complete view of the agent status when the issue happened with a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) from the affected agent

**Comment by yaronlev171** [comment]
@olivielpeau no, it has not happened again, and I have no idea how to get you that info you requested. closing.
