### ISSUE TITLE
Remove the fork from upstream repo

### ISSUE THREAD

**Issue by masci** [DataDog/gohai#49]
This repo is 80 commits ahead of the original fork, the name is different and also the scope has changed so it might be useful to cut the fork.

cc @irabinovitch

**Comment by jeremy-lq** [comment]
After chatting with masci I've submitted a request to detach this fork.

**Comment by jeremy-lq** [comment]
The request has been completed.

**Comment by masci** [comment]
Thanks @jeremy-lq !
