### ISSUE TITLE
Nil deref causing panics

### ISSUE THREAD

**Issue by andor44** [DataDog/gohai#66]
I started getting [panics](https://gist.github.com/andor44/cbfb0749091a84d1455c6bf072d96d88) on [here](https://github.com/DataDog/gohai/blob/bc98f936c76570e79c1c7e739425ff22ab2ee4a3/filesystem/filesystem.go#L48).

[`getFileSystemInfo`](https://github.com/DataDog/gohai/blob/bc98f936c76570e79c1c7e739425ff22ab2ee4a3/filesystem/filesystem.go#L14-L57) tries to run `df` with [`os/exec.Command`](https://golang.org/pkg/os/exec/#Command). Given where it's nil-derefing I assume it's not `cmd` that's nil but `cmd.Process` instead. Probably the process failed to start to begin with and that's why it's `nil` but I'm not familiar with this API so I can't say for sure.

**Comment by olivielpeau** [comment]
I believe this was fixed in https://github.com/DataDog/gohai/pull/68, which was released in Agent v6.11 (https://github.com/DataDog/datadog-agent/pull/3296) so closing this out (sorry for the extremely slow response on this)
