### ISSUE TITLE
DF warnings cause collector to fail 

### ISSUE THREAD

**Issue by rickalm** [DataDog/gohai#71]
The filesystem collector is overly sensitive to issues, reporting an error for an non-zero exit code without exploring the output for validity.

The issue I provided below is quite common with Docker and a CSI plugin such as RexRay where some mounts become disconnected. Disconnected mounts are completely acceptable in *nix, but gohai is suffering

$ gohai
[filesystem] df failed to collect filesystem data: exit status 1

$ df
df: ‘/var/lib/docker/plugins/c7d1f9a51a3e8168a67e3aebbef7f7d862cbfc30cdd6313c05c8f16fbc3a0be3/propagated-mount/volumes/metering-dev-influxdb-backup-influxs3bucket-dddd’: Transport endpoint is not connected
df: ‘/var/lib/docker/plugins/c7d1f9a51a3e8168a67e3aebbef7f7d862cbfc30cdd6313c05c8f16fbc3a0be3/propagated-mount/volumes/metering-dev-influxdb-backup-influxs3bucket-dddd’: Transport endpoint is not connected
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/nvme0n1p1  20960236 7902956  13057280  38% /
devtmpfs         3801376       0   3801376   0% /dev
tmpfs            3824268       0   3824268   0% /dev/shm
tmpfs            3824268  368500   3455768  10% /run
tmpfs            3824268       0   3824268   0% /sys/fs/cgroup

**Comment by ls-justin-bull** [comment]
Getting the same error:
> [filesystem] df failed to collect filesystem data: exit status 1

Considering this issue hasn't been address or acknowledged in a year does not give me hope.
My solution was to disable gohai.

**Comment by olivielpeau** [comment]
Hi, thanks for reporting this issue, and sorry for the slow response. We'll triage the issue and work on it once a fix is prioritized.

We'd be happy to review a PR if you'd like to contribute code. Thanks!

**Comment by pgimalac** [comment]
Hello, this repository has been archived, the gohai library now lives in https://github.com/DataDog/datadog-agent/pkg/gohai, feel free to re-open your issue in https://github.com/DataDog/datadog-agent if it is still relevant.
